#ifndef DEVICES_H
#define DEVICES_H

// Device type enumeration
typedef enum {
    DEVICE_ELECTROVALVE_A = 0,
    DEVICE_ELECTROVALVE_B,
    DEVICE_ELECTROVALVE_C,
    DEVICE_ELECTROVALVE_D,
    DEVICE_ELECTROVALVE_E,
    DEVICE_ELECTROVALVE_F,
    DEVICE_PUMP_PE,
    DEVICE_PUMP_PD,
    DEVICE_PUMP_PV,
    DEVICE_PUMP_PP,
    DEVICE_LED_BE1_RED,
    DEVICE_LED_BE1_GREEN,
    DEVICE_LED_BE2_RED,
    DEVICE_LED_BE2_GREEN,
    DEVICE_LED_BD1_RED,
    DEVICE_LED_BD1_GREEN,
    DEVICE_LED_BD2_RED,
    DEVICE_LED_BD2_GREEN,
    DEVICE_LED_BH,
    DEVICE_MAX
} device_type_t;

static const uint8_t NB_PUMPS = 4;
static const uint8_t NB_ELECTROVALVES = 6;

#endif // DEVICES_H